# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Note CI

on:
  push:
    branches: [ master ]

jobs:
  upload:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: upload artifact
        uses: actions/setup-node@v1
        with:
          name: note files
          path: ${{ github.workspace }}
        
